#include "Localization.hpp"
#include <unordered_map>
#include <string>
#include <string_view>

namespace YimMenu::Localization
{
static const std::unordered_map<std::string_view, std::string_view> kExact = {
 {"Self","自己"},
 {"Vehicle","载具"},
 {"Teleport","传送"},
 {"Network","网络"},
 {"Players","玩家"},
 {"World","世界"},
 {"Recovery","恢复"},
 {"Settings","设置"},
 {"Debug","调试"},
 {"Home","主页"},
 {"Dashboard","仪表盘"},
 {"General","常规"},
 {"Misc","杂项"},
 {"Weapons","武器"},
 {"Weapon","武器"},
 {"Ammo","弹药"},
 {"Money","金钱"},
 {"Enabled","已启用"},
 {"Disabled","已禁用"},
 {"Enable","启用"},
 {"Disable","禁用"},
 {"Active","活动"},
 {"Inactive","未激活"},
 {"Add","添加"},
 {"Delete","删除"},
 {"Remove","移除"},
 {"Clear","清除"},
 {"Close","关闭"},
 {"Open","打开"},
 {"Save","保存"},
 {"Load","加载"},
 {"Apply","应用"},
 {"Reset","重置"},
 {"Back","返回"},
 {"Cancel","取消"},
 {"Confirm","确认"},
 {"Refresh","刷新"},
 {"Search","搜索"},
 {"Filter","筛选"},
 {"Select","选择"},
 {"Current","当前"},
 {"Default","默认"},
 {"Custom","自定义"},
 {"All","全部"},
 {"None","无"},
 {"Unknown!","未知！"},
 {"Categories","分类"},
 {"Category","分类"},
 {"Name","名称"},
 {"Description","描述"},
 {"Type","类型"},
 {"Value","数值"},
 {"Amount","数量"},
 {"Count","数量"},
 {"Index","索引"},
 {"Size","大小"},
 {"Distance","距离"},
 {"Speed","速度"},
 {"Position","位置"},
 {"Rotation","旋转"},
 {"Color","颜色"},
 {"Colors","颜色"},
 {"Scale","缩放"},
 {"Hotkey","快捷键"},
 {"Saved...","已保存……"},
 {"Triggerer","触发器"},
 {"Basket","购物篮"},
 {"Service","服务"},
 {"ACQUIRE","获取"},
 {"ADD_CONTRABAND","添加违禁品"},
 {"ALLOT","分配"},
 {"BUY_CASINO_CHIPS","购买赌场筹码"},
 {"BUY_CONTRABAND_MISSION","购买违禁品任务"},
 {"BUY_ITEM","购买物品"},
 {"BUY_PROPERTY","购买资产"},
 {"BUY_UNLOCK","购买解锁项"},
 {"BUY_VEHICLE","购买载具"},
 {"BUY_VEHICLE_MODS","购买载具改装"},
 {"BUY_WAREHOUSE","购买仓库"},
 {"CREATE_PLAYER_APPEARANCE","创建玩家外观"},
 {"DELETE_CHAR","删除角色"},
 {"EARN","获取收益"},
 {"EARN_LIMITED_SERVICE","获取限时服务收益"},
 {"GIVE","给予"},
 {"PURCH","购买"},
 {"RECOUP","收回"},
 {"REMOVE_CONTRABAND","移除违禁品"},
 {"RESET_BUSINESS_PROGRESS","重置企业进度"},
 {"SELL_CASINO_CHIPS","出售赌场筹码"},
 {"SELL_VEHICLE","出售载具"},
 {"SPEND","消费"},
 {"SPEND_LIMITED_SERVICE","消费限时服务"},
 {"UPDATE_BUSINESS_GOODS","更新企业货物"},
 {"UPDATE_STORAGE_DATA","更新仓储数据"},
 {"UPDATE_WAREHOUSE_VEHICLE","更新仓库载具"},
 {"USE","使用"},
 {"BEARD","胡须"},
 {"BLUSHER","腮红"},
 {"CASINO_CHIP_REASON","赌场筹码原因"},
 {"CASINO_CHIPS","赌场筹码"},
 {"CHEST_HAIR","胸毛"},
 {"CLOTH","服装"},
 {"CONTACTS","隐形眼镜"},
 {"CONTRABAND_FLAGS","违禁品标记"},
 {"CONTRABAND_MISSION","违禁品任务"},
 {"CONTRABAND_QNTY","违禁品数量"},
 {"CURRENCY_TYPE","货币类型"},
 {"DATA_STORAGE","数据存储"},
 {"DECORATION","装饰"},
 {"EARN_CURRENCY","获取货币"},
 {"EYEBROWS","眉毛"},
 {"FACEPAINT","面部彩绘"},
 {"HAIR","头发"},
 {"INVENTORY_BEARD","库存胡须"},
 {"INVENTORY_BLUSHER","库存腮红"},
 {"INVENTORY_CHEST_HAIR","库存胸毛"},
 {"INVENTORY_CONTACTS","库存隐形眼镜"},
 {"INVENTORY_CONTRABAND_MISSION","库存违禁品任务"},
 {"INVENTORY_CURRENCY","库存货币"},
 {"INVENTORY_EYEBROWS","库存眉毛"},
 {"INVENTORY_FACEPAINT","库存面部彩绘"},
 {"INVENTORY_HAIR","库存头发"},
 {"INVENTORY_ITEM","库存物品"},
 {"INVENTORY_LIPSTICK","库存口红"},
 {"INVENTORY_MKUP","库存化妆品"},
 {"INVENTORY_PRICE_PAID","库存已付价格"},
 {"INVENTORY_PROPERTY","库存资产"},
 {"INVENTORY_PROPERTY_INTERIOR","库存资产室内"},
 {"INVENTORY_VEHICLE","库存载具"},
 {"INVENTORY_VEHICLE_MOD","库存载具改装"},
 {"INVENTORY_WAREHOUSE","库存仓库"},
 {"INVENTORY_WAREHOUSE_INTERIOR","库存仓库室内"},
 {"LIPSTICK","口红"},
 {"MART","商店"},
 {"MKUP","化妆品"},
 {"PRICE_MODIFIER","价格修正"},
 {"PRICE_OVERRIDE","价格覆盖"},
 {"PROPERTY_INTERIOR","资产室内"},
 {"SERVICE_UNLOCKED","已解锁服务"},
 {"SERVICE_WITH_LIMIT","限额服务"},
 {"SERVICE_WITH_THRESHOLD","阈值服务"},
 {"SYSTEM","系统"},
 {"TATTOO","纹身"},
 {"UNLOCK","解锁"},
 {"VEHICLE","载具"},
 {"VEHICLE_MOD","载具改装"},
 {"VEHICLE_UPGRADE","载具升级"},
 {"VENDING_MACHINE","自动售货机"},
 {"WAREHOUSE_INTERIOR","仓库室内"},
 {"WAREHOUSE_VEHICLE_INDEX","仓库载具索引"},
 {"WEAPON","武器"},
 {"WEAPON_AMMO","武器弹药"},
 {"WEAPON_MOD","武器改装"},
 {"UNKNOWN","未知"},
 {"Loaded successfully","加载成功"},
 {"Chat","聊天"},
 {"Challenges","挑战"},
 {"Casino","赌场"},
 {"Bounty","悬赏"},
 {"Remove LSC Restrictions","移除改车王限制"},
 {"Clear Chat","清空聊天"},
 {"Allow MP Vehicles in SP","允许单人模式使用线上载具"},
 {"Give Max Ammo","补满弹药"},
 {"Super Run","超级奔跑"},
 {"Infinite Parachutes","无限降落伞"},
 {"Weapon Explosion Radius","武器爆炸范围"},
 {"Format Money","金钱格式化"},
 {"Disable Action Mode","禁用动作模式"},
 {"Super Jump","超级跳跃"},
 {"Skip Conversation","跳过对话"},
 {"No Ragdoll","无布娃娃"},
 {"Fill Inventory","填充物品栏"},
 {"Heal","治疗"},
 {"Stand On Vehicles","站在载具上"},
 {"Clear Damage","清除污渍与血迹"},
 {"Rapid Fire","快速射击"},
 {"Skip Cutscene","跳过过场动画"},
 {"Infinite Special Ability","无限特殊能力"},
 {"Give All Weapons","获得全部武器"},
 {"Enable Special Abilities in MP","在多人游戏中启用特殊能力"},
 {"Open Gun Locker","打开武器柜"},
 {"Freecam","自由视角"},
 {"Clear Wanted","清除通缉"},
 {"Set Wanted","设置通缉等级"},
 {"Never Wanted","永不被通缉"},
 {"Freeze Wanted","冻结通缉等级"},
 {"No Idle Kick","防止挂机踢出"},
 {"Keep Player Clean","保持角色清洁"},
 {"Suicide","自杀"},
 {"Infinite Ammo","无限弹药"},
 {"God Mode","上帝模式"},
 {"Infinite Clip","无限弹匣"},
 {"No Clip","穿墙模式"},
 {"Explosive Ammo","爆炸弹药"},
 {"Unlimited Oxygen","无限氧气"},
 {"Invisibility","隐身"},
 {"Open Wardrobe","打开衣柜"},
 {"Weapon Damage","武器伤害"},
 {"Off The Radar","雷达隐身"},
 {"Disable Critical Hits","禁用暴击"},
 {"Mobile Radio","移动电台"},
 {"Aimbot","自瞄"},
 {"Aim For Head","瞄准头部"},
 {"Target Drivers","瞄准驾驶员"},
 {"Modify Boost Behavior","修改加速行为"},
 {"Despawn Personal Vehicle","收回个人载具"},
 {"Allow Hats In Vehicles","允许在载具内佩戴帽子"},
 {"Repair Vehicle","修复载具"},
 {"Request Personal Vehicle","召唤个人载具"},
 {"Keep Vehicle Fixed","保持载具完好"},
 {"Seatbelt","安全带"},
 {"Fix All Vehicles","修复所有载具"},
 {"Horn Boost","喇叭加速"},
 {"Enable All DLC Vehicles","启用全部DLC载具"},
 {"Lower Vehicle Stance","降低载具姿态"},
 {"Save Personal Vehicle","保存个人载具"},
 {"Vehicle God Mode","载具无敌"},
 {"Speedometer","速度计"},
 {"Enter Last Vehicle","进入上次载具"},
 {"Call Mechanic","呼叫技工"},
 {"Set All Activities Completed","完成全部活动"},
 {"Reset All Activities","重置全部活动"},
 {"Complete All Challenges","完成全部挑战"},
 {"Teleport to Hidden Cache","传送至隐藏缓存"},
 {"Collect Hidden Cache","收集隐藏缓存"},
 {"Teleport to Treasure Chest","传送至宝箱"},
 {"Collect Treasure Chest","收集宝箱"},
 {"Enable Treasure Chests in LS","在洛圣都启用宝箱"},
 {"Teleport to Shipwreck","传送至沉船"},
 {"Collect Shipwreck","收集沉船"},
 {"Teleport to Buried Stash","传送至埋藏储藏物"},
 {"Collect Buried Stash","收集埋藏储藏物"},
 {"Enable Buried Stashes in LS","在洛圣都启用埋藏储藏物"},
 {"Teleport to Skydive","传送至跳伞点"},
 {"Complete Skydive","完成跳伞"},
 {"Teleport to Time Trial","传送至计时赛"},
 {"Beat Time Trial","完成计时赛"},
 {"Teleport to Exotic Exports Vehicle","传送至特殊货物载具"},
 {"Deliver Next Exotic Exports Vehicle","交付下一辆特殊货物载具"},
 {"Teleport to G's Cache","传送至G的缓存点"},
 {"Collect G's Cache","收集G的缓存"},
 {"Teleport to Stash House","传送至藏匿屋"},
 {"Enter Stash House Safe Code","输入藏匿屋保险箱密码"},
 {"Teleport to Dealer","传送至街头毒贩"},
 {"Open Street Dealer Menu","打开街头毒贩菜单"},
 {"Teleport to LS Tag","传送至洛圣都涂鸦"},
 {"Spray LS Tag","喷涂洛圣都涂鸦"},
 {"Teleport to Madrazo Hit","传送至马德拉索刺杀任务"},
 {"Teleport to Madrazo Hit Target","传送至马德拉索刺杀目标"},
 {"Spawn Animal","生成动物"},
 {"Photograph Animal","拍摄动物"},
 {"Teleport to Product","传送至货物"},
 {"Collect Product","收集货物"},
 {"Teleport to Golden Clover","传送至金色四叶草"},
 {"Collect Golden Clover","收集金色四叶草"},
 {"Claim Safe Earnings","领取保险箱收益"},
 {"Allow Gender Change","允许更改性别"},
 {"Manipulate Rig Slot Machines","操纵老虎机"},
 {"No Change Appearance Cooldown","取消外观更改冷却"},
 {"Override RP Multiplier","覆盖RP倍率"},
 {"Play All Missions Solo","单人完成全部任务"},
 {"Change Appearance For Free","免费更改外观"},
 {"Unlock GTA+","解锁GTA+"},
 {"Set Cuts","设置分成"},
 {"Force Ready","强制准备"},
 {"Setup","设置任务"},
 {"Set Primary Target Value","设置主要目标价值"},
 {"Set Secondary Take Value","设置次要战利品价值"},
 {"Skip Hacking","跳过破解"},
 {"Cut Sewer","切断下水道"},
 {"Cut Glass","切割玻璃"},
 {"Take Primary Target","拿取主要目标"},
 {"Instant Finish","立即完成"},
 {"Gunman","枪手"},
 {"Approach","接近方式"},
 {"Driver","车手"},
 {"Hacker","黑客"},
 {"Set Potential Take","设置潜在收益"},
 {"Set Actual Take","设置实际收益"},
 {"Skip Drilling","跳过钻孔"},
 {"Solo Mantrap","单人天花板通道"},
 {"Manchez","Manchez摩托车"},
 {"Skip Fingerprint Hack","跳过指纹破解"},
 {"Skip Signal Nodes","跳过信号节点"},
 {"Skip Data Crack","跳过数据破解"},
 {"Disable Laser Grid","禁用激光网"},
 {"Take Secondary Target","拿取次要目标"},
 {"Auto-Enter PC Access Code","自动输入电脑访问码"},
 {"Skip Swiping","跳过刷卡"},
 {"Instant Finish (Pacific)","立即完成（太平洋标准）"},
 {"Teleport to Objective","传送至目标"},
 {"Teleport to Waypoint","传送至导航点"},
 {"Auto Teleport to Waypoint","自动传送至导航点"},
 {"Teleport Forward","向前传送"},
 {"Teleport Backward","向后传送"},
 {"Teleport Right","向右传送"},
 {"Teleport Left","向左传送"},
 {"Teleport Up","向上传送"},
 {"Teleport Down","向下传送"},
 {"Force Script Host","强制脚本主机"},
 {"Force Thunder","强制雷暴"},
 {"Pause Game","暂停游戏"},
 {"Dump Data Hash","导出数据哈希"},
 {"Spoof Data Hash","伪造数据哈希"},
 {"Disable Death Barriers","禁用死亡边界"},
 {"Spoof Matchmaking Region","伪造匹配地区"},
 {"Harass Players","骚扰玩家"},
 {"Bypass Casino Restrictions","绕过赌场限制"},
 {"Fast Join","快速加入"},
 {"Join YimMenu-only Sessions","加入仅限YimMenu的会话"},
 {"Spam Killfeed","刷屏击杀信息"},
 {"Silence Phone Calls","静音电话"},
 {"Join Session","加入会话"},
 {"Spectate","观战"},
 {"Delete Vehicle","删除载具"},
 {"Set Bounty","设置悬赏"},
 {"Give Weapons","给予武器"},
 {"Send Phantom Car","发送幽灵车"},
 {"Send Gooch","发送Gooch"},
 {"Send Sext","发送色情短信"},
 {"Send to Interior","传送至室内"},
 {"Teleport to Player","传送至玩家"},
 {"Bring","拉到身边"},
 {"Send to Property","传送至资产"},
 {"Teleport Player To Coord","将玩家传送至坐标"},
 {"Kill","击杀"},
 {"Explode","引爆"},
 {"CEO Kick","CEO踢出"},
 {"Permadeath","永久死亡"},
 {"Blackscreen","黑屏"},
 {"Script Host Kick","脚本主机踢出"},
 {"Freemode State Kick","自由模式状态踢出"},
 {"Null Function Kick","空函数踢出"},
 {"Host Kick","主机踢出"},
 {"Kill All Peds","击杀所有NPC"},
 {"Kill All Enemies","击杀所有敌人"},
 {"Cops Dispatch","警察调度"},
 {"Infinite Boundary","无限边界"},
 {"Spawn Ped","生成NPC"},
 {"Spawn Object","生成物体"},
 {"IPL","IPL"},
 {"Load IPL","加载IPL"},
 {"Unload IPL","卸载IPL"},
 {"Teleport to IPL","传送至IPL"},
 {"Bring All Objects","拉取所有物体"},
 {"Bring All Peds","拉取所有NPC"},
 {"Bring All Vehicles","拉取所有载具"},
 {"Riot Mode","暴动模式"},
 {"Peds Ignore","NPC无视"},
 {"Set Weather","设置天气"},
 {"Force Weather","强制天气"},
 {"Delete All Objects","删除所有物体"},
 {"Delete All Peds","删除所有NPC"},
 {"Delete All Vehicles","删除所有载具"},
 {"Set Time","设置时间"},
 {"Freeze Time","冻结时间"},
 {"Enable Creator Dev Mode","启用编辑器开发者模式"},
 {"Update Saved Players Now","立即更新已保存玩家"},
 {"Blocks all incoming damage","阻止所有受到的伤害"},
 {"Allows you to fly through the map","允许你穿越地图自由飞行"},
 {"Be invisible","使角色隐身"},
 {"Jump higher than normal","比正常情况下跳得更高"},
 {"Run faster than normal","比正常情况下跑得更快"},
 {"Always have a parachute","始终拥有降落伞"},
 {"You will never run out of ammo","弹药永远不会耗尽"},
 {"Have an endless clip in your gun","武器弹匣弹药无限"},
 {"Allows you to stay underwater without losing oxygen.","允许你在水下停留而不会消耗氧气"},
 {"Prevents you from ragdolling","防止角色进入布娃娃状态"},
 {"Clears all the dirt and blood on you.","清除角色身上的污渍和血迹"},
 {"Kills you","立即击杀自己"},
 {"Gives you all weapons","给予你全部武器"},
 {"Allows you to access your wardrobe remotely.","允许你远程打开衣柜"},
 {"Hides you from other players on the radar","让你在其他玩家的雷达上隐身"},
 {"Allows altering your weapons damage output","允许修改武器造成的伤害"},
 {"Allows you to listen to any radio station on foot with Hotkey Q","允许你步行时通过 Q 键收听任意电台"},
 {"Locks on to enemies and other players","自动锁定敌人和其他玩家"},
 {"Targets the head when locking on to enemies and other players","锁定敌人和其他玩家时瞄准头部"},
 {"Allows aimbot to lock on to enemies and other players in vehicles","允许自瞄锁定载具中的敌人和其他玩家"},
 {"Failed to join session","加入会话失败"},
 {"An existing transition is in progress","已有会话切换正在进行中"},
 {"Failed to get session info by RID","无法通过R星ID获取会话信息"},
 {"Entity is not a ped.","实体不是NPC。"},
 {"Player entity cannot be deleted.","无法删除玩家实体。"},
 {"Entity is too far.","实体距离太远。"},
 {"Gravity gun cannot be applied on player entity.","无法对玩家实体使用重力枪。"},
 {"Invalid vehicle.","无效的载具。"},
 {"No vehicle model name provided.","未提供载具模型名称。"},
 {"Invalid vehicle model name provided.","提供的载具模型名称无效。"},
 {"Please join GTA Online.","请先进入GTA在线模式。"},
 {"Cannot open gun locker while in an interior.","处于室内时无法打开武器柜。"},
 {"Not safe to open the wardrobe at the moment.","当前不适合打开衣柜。"},
 {"Failed to open the wardrobe.","打开衣柜失败。"},
 {"No vehicles to fix.","没有需要修复的载具。"},
 {"Please get in a vehicle.","请先进入载具。"},
 {"This vehicle cannot be saved as a personal vehicle.","此载具无法保存为个人载具。"},
 {"This vehicle is already a personal vehicle.","此载具已经是个人载具。"},
 {"Not safe to call the mechanic at the moment.","当前不适合呼叫技工。"},
 {"Failed to call the mechanic.","呼叫技工失败。"},
 {"No model name provided.","未提供模型名称。"},
 {"Invalid model name provided.","提供的模型名称无效。"},
 {"Select a file first","请先选择一个文件。"},
 {"File does not exist.","文件不存在。"},
 {"Loaded succesfully","加载成功"},
};

std::string Translate(std::string_view text)
{
 auto it = kExact.find(text);
 if (it != kExact.end())
  return std::string(it->second);
 return std::string(text);
}
}
